-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/",C.BOARD_ID,"/",C.FILE_ID,C.FILE_NAME,C.FILE_EXT) AS FILE_PATH
FROM (
    SELECT B.*
    FROM USED_GOODS_BOARD A JOIN USED_GOODS_FILE B
    USING(BOARD_ID)
    WHERE A.VIEWS= (
        SELECT VIEWS
        FROM USED_GOODS_BOARD
        ORDER BY VIEWS DESC
        LIMIT 1
    )
) C
ORDER BY C.FILE_ID DESC


